services:
  db:
    image: postgres:15
    container_name: crypto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - "com.crypto.description=PostgreSQL databáza pre kryptomeny"
      - "com.crypto.service=databáza"
      - "com.crypto.version=1.0"
      - "com.crypto.maintainer=Admin"
      - "com.crypto.environment=production"
      - "com.crypto.healthcheck=true"
      - "com.crypto.backup=true"
      - "com.crypto.volume=postgres_data"

  redis:
    image: redis:7
    container_name: crypto_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - "com.crypto.description=Redis cache pre kryptomeny"
      - "com.crypto.service=cache"
      - "com.crypto.version=1.0"
      - "com.crypto.maintainer=Admin"
      - "com.crypto.environment=production"
      - "com.crypto.healthcheck=true"

  api:
    build: .
    container_name: crypto_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - COINGECKO_API_URL=${COINGECKO_API_URL}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8000}:8000"
    command: >
      sh -c "python -c 'import time; time.sleep(5)' &&
             python -c 'from database import engine; from schemas import Base; Base.metadata.create_all(bind=engine)' &&
             uvicorn main:app --host ${APP_HOST} --port ${APP_PORT} --reload"
    labels:
      - "com.crypto.description=FastAPI aplikácia pre správu kryptomien"
      - "com.crypto.service=api"
      - "com.crypto.version=1.0"
      - "com.crypto.maintainer=Admin"
      - "com.crypto.environment=production"
      - "com.crypto.healthcheck=true"
      - "com.crypto.documentation=http://localhost:${APP_PORT:-8000}/docs"
      - "com.crypto.api=true"
      - "com.crypto.coingecko=true"

volumes:
  postgres_data:
    labels:
      - "com.crypto.description=Trvalé úložisko pre PostgreSQL databázu"
      - "com.crypto.service=storage"
      - "com.crypto.backup=true"
  redis_data:
    labels:
      - "com.crypto.description=Trvalé úložisko pre Redis cache"
      - "com.crypto.service=storage"
      - "com.crypto.backup=true" 